export const SET_NEW_CONTACTS = "SET_NEW_CONTACTS"
export const SET_FILTER_CONTACT ="SET_FILTER_CONTACT"
export const SET_FILTER ="SET_FILTER"
export const SET_DETAILED_FILTERED_CONTACTS ="SET_DETAILED_FILTERED_CONTACTS" 